version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: tp-redis
    ports:
      - "6379:6379"

  data-loader:
    build: ./data_loader
    container_name: tp-data-loader
    environment:
      # <—----------  CHANGE THESE  ----------->
      FMP_API_KEY: "sWzM15DYnUEke7zhQsnxnGqx1xw4b9Pu"
      SYMBOL: "EURUSD,GBPUSD,USDJPY,USDCAD,USDAUD"
      LOADER_INTERVAL: 3600     # seconds; use 30 while testing
    depends_on:
      - redis

  data-retainer:
    build: ./data_retainer
    container_name: tp-data-retainer
    depends_on: [redis]
    environment:
      REDIS_HOST: redis
      SYMBOLS: ${SYMBOLS}           # reuse the same list as loader
      RETAINER_INTERVAL: 3600       # every hour; use 300 for dev
      ARCHIVE_DIR: /archive
    volumes:
      - ./history:/archive          # host-side folder for CSVs

      