services:
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--save", "300", "1", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data

  data_loader:
    build:
      context: .
      dockerfile: ./data_loader/Dockerfile
    env_file: .env
    depends_on: [redis]
    restart: unless-stopped

  data_retainer:
    build:
      context: .
      dockerfile: data_retainer/Dockerfile
    env_file: .env
    depends_on: [redis]
    volumes:
      - ./history:/app/history           # ⟵ host folder
    restart: unless-stopped

  model_service:
    build:
      context: .
      dockerfile: model_service/Dockerfile
    env_file: .env
    depends_on: [redis, data_loader]
    restart: unless-stopped

  decision_service:
    build:
      context: .
      dockerfile: decision_service/Dockerfile
    env_file: .env
    depends_on: [redis, model_service]
    restart: unless-stopped

  trade_executor:
    build:
      context: .
      dockerfile: trade_executor/Dockerfile
    env_file: .env
    depends_on: [redis, decision_service]
    restart: unless-stopped

  trade_manager:
    build:
      context: .
      dockerfile: trade_manager/Dockerfile
    env_file: .env
    depends_on: [redis, trade_executor]
    restart: unless-stopped
    ports:
      - "8000:8000"

volumes:
  redis_data:
