version: "3.9"

services:
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--save", "300", "1", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    restart: unless-stopped

  data_loader:
    build: ./data_loader
    env_file: .env
    depends_on: [redis]
    restart: unless-stopped

  data_retainer:
    build: ./data_retainer
    env_file: .env
    depends_on: [redis]
    restart: unless-stopped

  model_service:
    build: ./model_service
    env_file: .env
    depends_on: [redis, data_loader]
    restart: unless-stopped

  decision_service:
    build: ./decision_service
    env_file: .env
    depends_on: [redis, model_service]
    restart: unless-stopped

  trade_executor:
    build: ./trade_executor
    env_file: .env
    depends_on: [redis, decision_service]
    restart: unless-stopped

  trade_manager:
    build: ./trade_manager
    env_file: .env
    depends_on: [redis, trade_executor]
    restart: unless-stopped
    ports:
      - "8000:8000"   # only if you want the REST API accessible

volumes:
  redis_data:
